config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :users

  resources :gists

  root 'gists#index'

  get "register" => "users#new",        :as => "register"
  get "login"    => "sessions#new",     :as => "login"
  get "logout"   => "sessions#destroy", :as => "logout"
  resources :users
  resources :sessions
end

app/models/gist.rb
class Gist < ActiveRecord::Base

def self.search(search)
  if search
    where('description LIKE ?', "%#{search}%")
  else
    where('')
  end
end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, uniqueness: true, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user # make it visible in views
  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  private
  def login_required
  unless current_user
    flash[:alert] = "You must first log in or register before accessing this page."
    redirect_to login_url
  end
end
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
  before_action :set_gist, only: [:show, :edit, :update, :destroy]
  before_filter :login_required, :except => [:index, :show]
   # GET /gists
  # GET /gists.json
  def index
      @gists = Gist.search(params[:search]).paginate(page: params[:page], per_page: 10).order('created_at DESC')
      respond_to do |format|
      format.html
      format.js
    end
end

#  @gists = Gist.all
#  end

  # GET /gists/1
  # GET /gists/1.json
  def show
  end

  # GET /gists/new
  def new
    @gist = Gist.new
  end

  # GET /gists/1/edit
  def edit
  end

  # POST /gists
  # POST /gists.json
  def create
    @gist = Gist.new(gist_params)

    respond_to do |format|
      if @gist.save
        format.html { redirect_to @gist, notice: 'Kod został poprawnie dodany.' }
        format.json { render action: 'show', status: :created, location: @gist }
      else
        format.html { render action: 'new' }
        format.json { render json: @gist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gists/1
  # PATCH/PUT /gists/1.json
  def update
    respond_to do |format|
      if @gist.update(gist_params)
        format.html { redirect_to @gist, notice: 'Kod został poprawnie zaktualizowany.' }
        format.json { render action: 'show', status: :ok, location: @gist }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gists/1
  # DELETE /gists/1.json
  def destroy
    @gist.destroy
    respond_to do |format|
      format.html { redirect_to gists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gist
      @gist = Gist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gist_params
      params.require(:gist).permit(:snippet, :lang, :description)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 def create
    user = User.find_by_email(params[:sessions][:email])
    if user && user.authenticate(params[:sessions][:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash[:notice] = "Nieprawidłowy email lub hasło!"
      render "new"
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(comment_params)
    if @user.save
      redirect_to root_url, notice: "Thank you for registering!"
    else
      render "new"
    end
  end
private
  def comment_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/views/gists/_form.html.erb
<%= form_for(@gist) do |f| %>

<%
  all_lexers = Pygments.lexers.flatten.select.with_index(offset = 0) { |x,i| i % 2 == 0 }.sort
  all_lexers = all_lexers.delete_if { |x| x =~ /.\s./ }
  all_lexers = all_lexers.map { |x| x.downcase }
%>

  <% if @gist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gist.errors.count, "error") %> prohibited this gist from being saved:</h2>

      <ul>
      <% @gist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :kod %><br>
    <%= f.text_area :snippet %>
  </div>
  <div class="field">
    <%= f.label :opis %><br>
    <%= f.text_field :description, :maxlength => 100 %>
  </div>
  <div class="field">
    <%= f.label :język %><br>
    <%= f.select :lang, all_lexers %>
  </div>
<br>
  <div class="actions">
    <%= f.submit 'Zatwierdź', data: { confirm: 'Czy na pewno zachować wprowadzone zmiany?' }, :class => "btn btn-success btn-lg" %>
  </div>
<br>
<% end %>

app/views/gists/_gist.html.erb
      <tr class="gist">
        <td><%= raw Pygments.highlight(gist.snippet.length > 80 ? gist.snippet[0,80] + "..." : gist.snippet, lexer: gist.lang) %></td>
        <td><%= gist.lang %></td>
        <td><%= gist.description %></td>
        <td><%= link_to 'Wyświetl', gist,  :class => "btn btn-info  btn-lg" %></td>
        <td><%= link_to 'Edytuj', edit_gist_path(gist), :class => "btn btn-warning  btn-lg" %></td>
        <td><%= link_to 'Usuń', gist, method: :delete, data: { confirm: 'Czy na pewno usunąć?' }, :class => "btn btn-danger btn-lg" %></td>
      </tr>

app/views/gists/edit.html.erb
<h1>Edytuj kod</h1>

<%= render 'form' %>

<%= link_to 'Wyświetl', @gist, data: { confirm: 'Wszelkie niezachowane zmiany zostaną utracone!' }, :class => "btn btn-info" %>
<%= link_to 'Cofnij', gists_path, data: { confirm: 'Wszelkie niezachowane zmiany zostaną utracone!' }, :class => "btn btn-danger" %>

app/views/gists/index.html.erb
<br />
<%= link_to 'Dodaj kod', new_gist_path, :class => "btn btn-success btn-lg btn-block" %>

<h1>Lista dodanych kodów</h1>

<table id="gists">
  <thead>
    <tr>
      <th>Kod</th>
      <th>Język</th>
      <th>Opis</th>
      <th colspan="3">Opcje</th>
    </tr>
  </thead>

  <tbody id="my-gists">
	<%= render @gists %>
  </tbody>
</table>

<div id="infinite-scrolling">
  <center><%= will_paginate %></center>
</div>

app/views/gists/index.js.erb
$('#my-gists').append('<%= j render @gists %>');
<% if @gists.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @gists %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>

app/views/gists/new.html.erb
<h1>Nowy kod</h1>

<%= render 'form' %>

<%= link_to 'Cofnij', gists_path, :class => "btn btn-danger" %>

app/views/gists/show.html.erb
<p id="noticewlasny"><%= notice %></p>
<p>
  <strong>Język:</strong>
  <%= @gist.lang %>
</p>
<p>
  <strong>Kod:</strong>
</p>
<%= raw Pygments.highlight(@gist.snippet, lexer: @gist.lang) %>
<p>
  <strong>Opis:</strong>
  <%= @gist.description %>
</p>
<%= link_to 'Edytuj', edit_gist_path(@gist), :class => "btn btn-warning" %>

<%= link_to 'Cofnij', gists_path, :class => "btn btn-danger" %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Projekt na zaliczenie przedmiotu "Architektura serwisów internetowych".
  </small>
  <small class="pull-right">
	&copy; Michał Lipowski
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top" style="padding: 5px; background-color: #083952">
  <div>
    <div class="container">
      	<a href="/gists" class="btn btn-primary btn-lg active" role="button">Strona główna</a>
	<a href="https://github.com/lipek92/PANDA5" class="btn btn-primary btn-lg active github" role="button">Projekt na Github'ie</a>
	<div class="pull-right" style="padding: 3px;">
  		<% if session[:user_id] %>
   		 <div class="logged-in">Zalogowany jako <%= current_user.email %></div> 
  		  <%= link_to "Wyloguj", session_path("current"), method: "delete" %>
  		<% else %>
   		 <%= link_to "Rejestracja", new_user_path %> |
   		 <%= link_to "Logowanie", new_session_path %>
 		 <% end %>
 		 <%= form_tag gists_path, :method => 'get',:class =>"form-search", :id => "gists_search" do %>
 		 <%= text_field_tag :search, params[:search], :class => 'input search-query'%>
  		<%= submit_tag "Szukaj", :name => nil, :class => 'btn btn-primary active' %>
  		<% end %>
	</div>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Gist - pierwsza aplikacja</title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container" style="margin-top: 20px;">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<h1>Rejestracja</h1>


<div class="errors">
  <% if @user.errors.full_messages.any? %>
      <% @user.errors.full_messages.each do |error_message| %>
          <p><%= error_message if @user.errors.full_messages.first == error_message %> </p>
      <% end %>
  <% end %>
</div>


<%= form_for @user do |f| %>
    <div class="inputs">
      <p>Email: </p>
      <p><%= f.text_field :email %></p>
      <p>Hasło: </p>
      <p><%= f.password_field :password %></p>
      <p>Powtórz hasło: </p>
      <p><%= f.password_field :password_confirmation %></p>
    </div>
    <div class="actions">
      <%= f.submit "Zarejestruj!", class: 'btn btn-primary' %>
    </div>
<% end %>